### ISSUE TITLE
hdfs canary was failing big league

### ISSUE THREAD

**Issue by J0nathan12** [clusterdock/framework#25]
deployed clusterdock on a centos 7 VM. got literally everything working perfect but the hdfs canary was failing, and there was something about the Namenode not being able to find its datanodes. I suspect its an incompatibility b/n 7 and 6. logs for name node said: 

Failed to find datanode (scope="" excludedScope="/default"). //excludes default scope??? 

Failed to place enough replicas, still in need of 1 to reach 2 (unavailableStorages=[DISK], storagePolicy=BlockStoragePolicy{HOT:7, storageTypes=[DISK], creationFallbacks=[], replicationFallbacks=[ARCHIVE]}, newBlock=false)

File /tmp/.cloudera_health_monitoring_canary_files/.canary_file_2017_06_12-18_01_01 could only be replicated to 0 nodes instead of minReplication (=1). There are 2 datanode(s) running and no node(s) are excluded in this operation.

**Comment by dimaspivak** [comment]
There shouldn't be any issue with running a Docker container based on one OS' image on a different operating system. What I suspect is happening here is that your Docker host is likely using `devicemapper`, which is renowned for how problematic it is for anything but very simple use cases. To check, run `docker info | grep "Storage Driver"`. The simplest fix in that case is to use a different host operating system. FWIW I've used Ubuntu as my preferred Docker host OS for years and have had nothing but great experiences.

**Comment by J0nathan12** [comment]
thank you. my other question: would it be possible to easily rewrite the scripts to deploy centos 7 containers?

**Comment by dimaspivak** [comment]
Sadly, nope. Impossible with how the images are currently created.
