### ISSUE TITLE
Distribute containers and volumes across cloud servers? 

### ISSUE THREAD

**Issue by J0nathan12** [clusterdock/framework#27]
i want to implement a cloudera instance that involves using docker containers for nodes, but i want to distribute them across different cloud servers. Could i create and modify them in one, then distribute them? I just want to know if its possible. I know that managing the data volumes would be a bit of a headache.

**Comment by dimaspivak** [comment]
Not currently possible. Issue #12 was opened a while back to add it, but it will require a substantial refactor of the framework.
